replicaCount: 1

image:
  repository: "otter-docs"
  pullPolicy: "Always"
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

git:
  url:
  branch:

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local