ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: example.indigo.tribbles.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: otter-docs-example-tls
     hosts:
       - example.indigo.tribbles.cloud