
image:
  repository: "tribblesregistry.azurecr.io/otter-docs"

git:
  url: "https://cblaettl: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@github.com/monostream/2pack-docs.git"

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: docs.indigo.tribbles.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: otter-docs-tls
     hosts:
       - docs.indigo.tribbles.cloud