git:
  url: "https://github.com/monostream/otter-docs-example.git"

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: docs.otter.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: otter-docs-tls
     hosts:
       - docs.otter.com