apiVersion: v1
kind: Service
metadata:
  name: {{ include "otter-docs-example.fullname" . }}
  labels:
    {{- include "otter-docs-example.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "otter-docs-example.selectorLabels" . | nindent 4 }}
